spring:
  profiles:
    group:
      local: local, secret
      dev: dev, secret
      test: test, secret
    default: local
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
  config:
    import:
      - ./application-secret.yml
logging:
  level:
    nemo: debug
