spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test"
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  security:
    user:
      password: 1234
